activeEnv: test_env
browser:
  browserName: firefox
  browserAttachScreenshot: false
  headlessMode: true
  browserTimeout: 60
environments:
  test_env:
    envName: test_env
    appUrl: https://www.filmweb.pl/
    title: Filmweb - filmy takie jak Ty!
  int_env:
    envName: int_env
    title: Selenium
    appUrl: https://www.selenium.dev/



